### PR TITLE
fix(#2181): Add awareness of ActionScope in clearing of particular caches

### LINKED ISSUE #2181: Confusing Clear cache functionality for multiple instances
**Enhancement**

https://github.com/codecentric/spring-boot-admin/pull/1785 adds a new toggle button for choosing to clear the cache on all instances or selected instance **(1)**. 

However, this functionality is applied only for the "Clear" button on top of the page, which clears all caches **(2)**. And not applied to particular caches "Clear" buttons in the list of all caches **(3)**.  

It seems confusing for us from the UX perspective. This toggle should be applied to all "Clear" buttons on the page
Screenshot 2022-12-16 at 14 53 40

### PR DESCRIPTION
**Pull request by psemeniuk**
Fixes #2181

### CODE REVIEW

**Comment by psemeniuk** [comment]
Hi @erikpetzold,
contributed as promised ;)  Could you take a look?

File: spring-boot-admin-server-ui/src/main/frontend/components/sba-action-button-scoped.vue [hunk 1]
```diff
@@ -121,6 +123,9 @@ export default {
         )
         .subscribe();
     },
+    emitScopeChanged(scope) {
+      this.$emit('scopeChanged', scope);
+    },
```
Comment (erikpetzold) [inline spring-boot-admin-server-ui/src/main/frontend/components/sba-action-button-scoped.vue:128]: If we already have this button and use it in other places, why do we need to add this event here?

@SteKoe is this the way to go or should something else be used for this feature?

Comment (psemeniuk) [reply spring-boot-admin-server-ui/src/main/frontend/components/sba-action-button-scoped.vue:128]: I'm not a frontend developer, but i think we need to propagate somehow actual scope. From what i've read in Vue docs - for `child -> parent` propagation we need to emit event with the change. Event is emitted, but other sba-action-button-scoped consumers aren't forced to consume, because it's optional.

Comment (SteKoe) [reply spring-boot-admin-server-ui/src/main/frontend/components/sba-action-button-scoped.vue:128]: After having a deeper look into the change, I guess this is a good approach to propagate the scope of the action button to surrounding components. It feels a little bit confusing, as I can now switch the scope for the entire page via one button at the top of the page, but this was requested ind #2181. So, I will merge this as is, thanks for your work and patience :)

**Review by SteKoe — APPROVED** [review]
