### PR TITLE
Fix/401 redirect on actuator requests

### LINKED ISSUE #1640: Failing request on metrics redirect to login page
Hi, first of all thanks for this software, it's amanzing !

We've noticed something weird after upgrading our spring-boot-admin instance from **2.3.1** to **2.4.0**: when browsing instance details, after a random delay ( 5 - 30s )  users are automatically redirected to the login page

console log: 

console

The metrics causing the errors are not always the same: 

- http://spring-boot-admin/instances/f4933231d1f3/actuator/metrics/jvm.memory.max?tag=area:heap
- http://spring-boot-admin/instances/f4933231d1f3/actuator/metrics/jvm.memory.used?tag=area:nonheap,id:Metaspace
- http://spring-boot-admin/instances/f4933231d1f3/actuator/metrics/jvm.threads.daemon

Instance details: 

- spring-boot-admin-server 2.4.0
- spring-boot 2.4.3
- java 11
- auth mod: LDAP

**Server configuration**: 

```
spring.boot.admin.monitor.status-interval = 30000
spring.boot.admin.monitor.status-lifetime = 30000
spring.boot.admin.monitor.default-timeout = 30000
spring.boot.admin.monitor.default-retries = 1
```

**Client configuration**: 

```
spring.boot.admin.client.url     = http://spring-boot-admin/
spring.boot.admin.client.enabled = true
spring.boot.admin.client.instance.metadata.tags.environment = production

management.info.git.mode                  = full
management.health.mail.enabled            = false
management.health.ldap.enabled            = false

management.endpoints.web.exposure.include = *
management.endpoint.health.show-details   = always
management.endpoint.liquibase.enabled     = false
management.endpoint.beans.enabled         = false
management.endpoint.caches.enabled        = false
management.endpoint.threaddump.enabled    = false
management.endpoint.shutdown.enabled      = false
management.endpoint.heapdump.enabled      = false
management.endpoint.conditions.enabled    = false
management.endpoint.jolokia.enabled       = false


spring.security.user.name         = springbootadmin-user
spring.security.user.password     = xxxxxxx
spring.boot.admin.client.username = ${spring.security.user.name}
spring.boot.admin.client.password = ${spring.security.user.password}
spring.boot.admin.client.instance.metadata.user.name        = ${spring.security.user.name}
spring.boot.admin.client.instance.metadata.user.password    = ${spring.security.user.password}
```

### PR DESCRIPTION
**Pull request by ulischulte**
closes #1640, #1691 and probably some other issues connected to redirects to login.

I corrected the predicate inside the redirectOn401 (isInstanceActuatorRequest didn't include the baseUrl and so the predicate never matched).
However - the existance of this predicate suggests that there was previously a reaction to a 401 at actuator endpoints (still don't know why it occurs though).
I added a retry for the subscriptions and the UI seems to be working correctly with these adjustments.

### CODE REVIEW

File: spring-boot-admin-server-ui/src/main/frontend/views/instances/httptrace/index.vue [hunk 1]
```diff
@@ -265,7 +266,13 @@ const addToFilter = (oldFilter, addedFilter) =>
       createSubscription() {
         const vm = this;
         return timer(0, 5000)
-          .pipe(concatMap(vm.fetchHttptrace))
+          .pipe(concatMap(vm.fetchHttptrace), retryWhen(
+            err => {
+              return err.pipe(
+                delay(1000),
+                take(2)
```
Comment (SteKoe) [inline spring-boot-admin-server-ui/src/main/frontend/views/instances/httptrace/index.vue:273]: in the previous implementation you chose `take(5)` instead of `2`. Is there any reason for doing this? Would it make sense to refactor the whole `pipe` implementation to a function which can be reused anywhere? Like as follows:

```
const pipeRetry = (stream) => pipe(concatMap(stream), retryWhen(
    err => {
      return err.pipe(
        delay(1000),
        take(5)
      )
    }));

return timer(0,5000).pipeRetry(vm.fetchHttptrace).subscribe(....);
```
