### PR TITLE
Fix scheduled tasks view

### LINKED ISSUE #4239: Bug: The scheduled tasks view seems broken
## Spring Boot Admin Server information

- **Version**: 3.4.5

- **Spring Boot version**: 3.4.5

- **Configured Security**: None

- **Webflux or Servlet application**: WebFlux

## Client information

- **Spring Boot versions**: 3.4.5

- **Used discovery mechanism**: Eureka

- **Webflux or Servlet application**: WebFlux

## Description

The scheduled tasks view seems broken, as shown in the picture below:
Image

The actuator is currently returning:
```json
{
  "cron": [
    {
      "runnable": {
        "target": "foo.bar.schedule.job.FooBarDailyCollectorJob@6d093b9e"
      },
      "expression": "0 0 10 * * *",
      "nextExecution": {
        "time": "2025-05-01T07:59:59.999178200Z"
      }
    },
    {
      "runnable": {
        "target": "foo.bar.schedule.job.FooBarMonthlyAggregatorJob@8ca8d66"
      },
      "expression": "0 0 11 L * *",
      "nextExecution": {
        "time": "2025-05-31T08:59:59.999178200Z"
      }
    },
    {
      "runnable": {
        "target": "foo.bar.schedule.job.FooBarGapDetectorJob@5132f4fe"
      },
      "expression": "0 0 12 * * *",
      "nextExecution": {
        "time": "2025-05-01T09:59:59.999178200Z"
      }
    }
  ],
  "fixedDelay": [],
  "fixedRate": [],
  "custom": []
}
```

### PR DESCRIPTION
**Pull request by ulischulte**
closes #4239

### CODE REVIEW

File: spring-boot-admin-server-ui/src/main/frontend/views/instances/scheduledtasks/scheduled-task-executions.vue [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+      :value="task.lastExecution.time"
+    />
+  </td>
+  <td class="font-mono text-sm">
+    <span
+      v-if="task.lastExecution"
+      role="status"
+      :class="
+        classNames('status-badge', task.lastExecution.status.toLowerCase())
+      "
```
Comment (hzpz) [inline spring-boot-admin-server-ui/src/main/frontend/views/instances/scheduledtasks/scheduled-task-executions.vue:20]: Since we don't need to conditionally join class names here, we could use simple string concatenation and get rid of the `classNames` dependency.
```suggestion
      :class="`status-badge ${task.lastExecution.status.toLowerCase()}`"
```

File: spring-boot-admin-server-ui/src/main/frontend/views/instances/scheduledtasks/scheduled-task-executions.spec.ts [hunk 2]
```diff
@@ -0,0 +1,87 @@
...
+
+import ScheduledTaskExecutions from '@/views/instances/scheduledtasks/scheduled-task-executions.vue';
+
+const SbaFormattedObjStub = {
+  name: 'SbaFormattedObj',
+  props: ['value'],
+  template: '<div class="formatted-obj">{{ value }}</div>',
+};
+
+describe('ScheduledTaskExecutions.vue', () => {
```
Comment (hzpz) [inline spring-boot-admin-server-ui/src/main/frontend/views/instances/scheduledtasks/scheduled-task-executions.spec.ts:12]:
```suggestion
describe('ScheduledTaskExecutions', () => {
```

**Review by hzpz — CHANGES_REQUESTED** [review]

File: spring-boot-admin-server-ui/src/main/frontend/views/instances/scheduledtasks/scheduled-task-executions.spec.ts (hunk 2 above)
Comment (ulischulte) [reply spring-boot-admin-server-ui/src/main/frontend/views/instances/scheduledtasks/scheduled-task-executions.spec.ts]: done

File: spring-boot-admin-server-ui/src/main/frontend/views/instances/scheduledtasks/scheduled-task-executions.spec.ts [hunk 3]
```diff
@@ -0,0 +1,65 @@
...
+    render(ScheduledTaskExecutions, {
+      props: { task: baseTask },
+    });
+
+    const lastExec = await screen.findByText('2024-05-31T12:00:00Z');
+    expect(lastExec).toBeVisible();
+
+    const statusBadge = await screen.findByRole('status');
+    expect(statusBadge.textContent).toBe('SUCCESS');
+    expect(statusBadge.className).toBe('status-badge success');
```
Comment (hzpz) [inline spring-boot-admin-server-ui/src/main/frontend/views/instances/scheduledtasks/scheduled-task-executions.spec.ts:31]:
```suggestion
    expect(statusBadge).toHaveTextContent('SUCCESS');
    expect(statusBadge).toHaveClass('status-badge success');
```

File: spring-boot-admin-server-ui/src/main/frontend/views/instances/scheduledtasks/scheduled-task-executions.spec.ts [hunk 4]
```diff
@@ -0,0 +1,65 @@
...
+      nextExecution: { time: '2024-06-01T12:00:00Z' },
+      lastExecution: { time: '2024-05-31T12:00:00Z', status: 'ERROR' },
+    };
+    render(ScheduledTaskExecutions, {
+      props: { task },
+    });
+
+    const statusBadge = await screen.findByRole('status');
+    expect(statusBadge.textContent).toBe('ERROR');
+    expect(statusBadge.className).toBe('status-badge error');
```
Comment (hzpz) [inline spring-boot-admin-server-ui/src/main/frontend/views/instances/scheduledtasks/scheduled-task-executions.spec.ts:63]:
```suggestion
    expect(statusBadge).toHaveTextContent('ERROR');
    expect(statusBadge).toHaveClass('status-badge error');
```

**Review by hzpz — APPROVED** [review]
